### PR TITLE
Fix and update the tests

### PR DESCRIPTION
**Pull request by renanbr**

### CODE REVIEW

**Comment by renanbr** [comment]
After an investigation, I saw that tests are failing because **only the first** embedded document in a list is translated properly (according to the `__pclass` definitions).

Is it a driver bug? Have I missed some configuration?

In other words, it's open to review.

**Comment by bjori** [comment]
That sounds like a driver bug.
Can you file a ticket on https://jira.mongodb.org/browse/PHPC/ for that to loop in @derickr and @jmikola (that are currently maintaining the driver)

**Comment by renanbr** [comment]
Ok. I've created two issues actually.

The first one, related directly to this case.
https://jira.mongodb.org/browse/PHPC-545

And also a question, maybe related to the first.
I was trying to run an update using the same object inserted.
https://jira.mongodb.org/browse/PHPC-546

**Comment by bjori** [comment]
Thanks.

I'm thinking I should merge both of the PRs as they appear to be correct, and then keep an eye on the two tickets you filed and trigger a new test build once they have been fixed & released

**Pull request merged**
